research_task:
  description: >
    Conduct a thorough research about {company}
    Make sure you find any interesting and relevant information given. Use Instagram to find out more information about {company}
  expected_output: >
    A list with the most relevant information about {company} and what they do
  agent: researcher


seo_task:
  description: >
    Review the context you got and format the output using your SEO knowledge
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    An report about {company}
  agent: seo_specialist


content_creator_task:
  description: >
    Review the context you got from the researcher and SEO specialist.
    Create a email that is to be sent to {company}
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    An email to {company} giving a good reason why they should order a custom serving board from Hung On Wood
  agent: content_creator

owner_task:
  description: >
    You are the owner of Hung On Wood, and you know business
  expected_output: >
    A overview of what Hung On Wood produces
  agent: >
    shop_owner